### ISSUE TITLE
Offer a method of destruction

### ISSUE THREAD

**Issue by SheepTester** [Gamepro5/photosphere.js#2]
## Expected behaviour

If a photosphere no longer is needed, there should be a way to destroy it to save memory. For example,

```js
photosphere.destroy()
```

## Actual behaviour

According to the code, there is no way to stop the constant rendering, so it'll continue trying to render the photosphere after it is no longer needed. The WebGLRenderer is also still kept; ideally it should be reusable or [disposed](https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.dispose). The `keydown` event listener also isn't removed, so they'll continue running whenever a key is pressed, along with newer event listeners. This also means references to the canvas and renderer are maintained and can't be garbage collected. Opening and closing multiple photospheres in sequence will likely result in... *problems*.

**Comment by SheepTester** [comment]
@Gamepro5 This is urgent!

**Comment by Gamepro5** [comment]
:neckbeard:

**Comment by SheepTester** [comment]
A test:

```js
for (let i = 0; i < 100; i++) {
  const photosphere = new LoadPhotosphere(path, canvasID)
  photosphere.destroy()
}
```

Interacting with the page shouldn't be laggy after the for loop finishes

**Comment by SheepTester** [comment]
:tada:
